### ISSUE TITLE
Getting a 403

### ISSUE THREAD

**Issue by chrisdeso** [codeack-nz/test-repo#12]
Why am I getting 403s?

**Comment by postman-support** [comment]
You must add authorization

via @ | Postman Support

**Comment by postman-support** [comment]
The password is: **43**

via @ | Postman Support

**Comment by xk0der** [comment]
Hey I wanna jump on this thread too!

**Comment by postman-support** [comment]
Please don't share passwords on a public forum, folks!

via @chrisdeso | Postman Support

**Comment by postman-support** [comment]
This should not sync back to ZD
once posted to GitHub

**Comment by xk0der** [comment]
This should sync back to ZD

**Comment by xk0der** [comment]
Okay this should sync back to ZD

**Comment by xk0der** [comment]
This one for sure  should sync back to ZD

**Comment by postman-support** [comment]
Test -2 This should not sync back to ZD
once posted to GitHub

**Comment by xk0der** [comment]
Hey @postman-support does this work?

**Comment by xk0der** [comment]
A comment with styling *bold*

some `code`

and some 
```
Code block
```
