### ISSUE TITLE
test #6

### ISSUE THREAD

**Issue by xk0der** [codeack-nz/test-repo#6]
This should preserve the tags

**Comment by postman-support** [comment]
This is a comment set by a bot!

**Comment by postman-support** [comment]
This is a comment set by a bot!

**Comment by postman-support** [comment]
This is a comment set by a bot!

**Comment by postman-support** [comment]
#github

This "comment" will be sent to GitHub (Not really - just testing at the moment)

**Comment by postman-support** [comment]
This should get synced

Postman | Product Support | New Zealand

Status Page | Learning Center | Bugs + Feature Requests | Community

**Comment by postman-support** [comment]
This is a comment





via @xk0der

**Comment by postman-support** [comment]
Hey you should be able to solve it using this

via @xk0der | Postman Support

**Comment by xk0der** [comment]
Okay - but does this sync back to your ticketing system?
