### ISSUE TITLE
Edge case testing

### ISSUE THREAD

**Issue by xk0der** [codeack-nz/test-repo#9]
Test to see what happens if label is assigned after a while

**Comment by xk0der** [comment]
Some test comment

**Comment by postman-support** [comment]
GitHub Issue Linked Internally
Data: 60896

**Comment by postman-support** [comment]
Comment syncing from Zendesk to GitHub

via @ | Postman Support

**Comment by xk0der** [comment]
GitHub to Zendesk Sync
